### ISSUE TITLE
python2-ecosystem missing profile

### ISSUE THREAD

**Issue by alexxa** [modularity-modules/python2#2]
`dnf module install python2-ecosystem` fails with 

Error: No profile specified for 'python2-ecosystem', please specify profile.

**Comment by ignatenkobrain** [comment]
I think this has nothing to do with python2-ecosystem, but rather bug in DNF...

**Comment by asamalik** [comment]
Profiles are optional.

They make sense with modules representing an application or service, like httpd, because you can install httpd.  However, it does not make sense with modules such as python2-ecosystem that only provide a set of libraries. This module should be just enabled, so the packages from it can be installed as dependencies for other apps/services, or by a developer.

**Comment by torsava** [comment]
Agreed.

@alexxa Can you file this bug for DNF?

**Comment by alexxa** [comment]
[1] was reported by @ncoghlan 

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1503030
